triplinker/accounts/urls.py
from django.urls import path, re_path, include

from .views import all_views as views


app_name = 'accounts'

urlpatterns = [
    # Home page.
    path('feed/', views.show_feed, name="feed"),

    # All users list.
    path('users/', views.all_users_list, name='all_users_list'),

    # SetAvatar.
    path('set-avatar/', views.set_avatar_view, name='set-avatar'),

    # User's photo gallery.
    path('users/<int:user_id>/photo-gallery/', views.photos_of_user,
         name='user-photo-gallery'),

    # A particular profile of user.
    path('users/<int:user_id>/', views.detail_profile,
         name="detail_profile"),

    # Friends system.
    path('users/<int:user_id>/incoming-friend-requests/',
         views.all_incoming_friquests_list, name="incoming-frequests"),
    path('users/<int:user_id>/outgoing-friend-riquests/',
         views.all_outgoing_friquests_list, name="outgoing-frequests"),
    path('users/<int:user_id>/friend-list/', views.friends_list,
         name="friends-list"),
    path('users/<int:user_id>/delete-friend/', views.delete_user_from_friends,
         name="delete-friend"),

    path('users/<int:user_id>/send-request/', views.send_request,
         name="send-frequest"),
    path('users/<int:user_id>/accept-request/', views.accept_friend_request,
         name="accept-frequest"),
    path('users/<int:user_id>/cancel-request/', views.cancel_friend_request,
         name="cancel-frequest"),
    path('users/<int:user_id>/delete-request/', views.delete_friend_request,
         name="delete-frequest"),

    # Followers and following.
    path('users/<int:user_id>/follow/', views.follow_user, name="follow"),
    path('users/<int:user_id>/unfollow/', views.unfollow_user, name="unfollow"),

    path('users/<int:user_id>/followers/', views.followers_list,
         name="followers-list"),
    path('users/<int:user_id>/following/', views.following_list,
         name="following-list"),

    # Profile, reg, auth.
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/', views.ActivateView.as_view(), name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(),
         name='profile_edit')
]


# Rest API
detail_profile_api_url = r'trip-linker-api/detail-profile/' \
                         r'(?P<user_id>\d{1,30})/?'
rest_api_patterns = [
    path('api-auth/', include('rest_framework.urls'),
         name='rest_framework'),
    re_path(r'(detail|profile|detail-profile)/(?P<user_id>\d+)/?',
            views.TLAccountDetail.as_view(),
            name='detail-profile-api')
]

urlpatterns += rest_api_patterns

triplinker/chat/urls.py
# Django modules.
from django.urls import path

# !Triplinker modules:

# Current app modules.
from .views import all_views as views


app_name = 'chat'

urlpatterns = [
    path('', views.messages_page, name='messages-page'),
    path('<int:user_id>/', views.messages_dialog_page,
         name='messages-dialog'),
    path('send-message-api/<int:user_id>/', views.send_message,
         name='send-message'),
    path('send-message-from-dialogs-page/',
         views.send_message_from_dialogs_page,
         name='send-message-from-dialogs-page'),
    path('get-all-messages-api/<int:user_id>/',
         views.get_all_messages, name='get-all-messages'),

    # GroupChat possibility.
    path('create-group-chat', views.create_group_chat,
         name='create-group-chat'),
    path('group-chats/', views.list_of_group_chats, name='group-chats'),
    path('<slug:chat_name_slug>/', views.particular_group_chat,
         name='particular-group-chat'),
    path('<slug:chat_name_slug>/send-message-group-chat-api/',
         views.send_message_in_group_chat, name='send-message-group-chat'),
    path('<slug:chat_name_slug>/get-all-messages-api/',
         views.get_all_messages_for_group_chat,
         name='get-all-messages-group-chat'),

    # GroupChat extra features.
    path('<slug:chat_name_slug>/participants/', views.view_participants,
         name='participants'),
    path('invite-person/<slug:chat_name_slug>/',
         views.invite_to_chat, name='invite-to-chat'),
    path('delete-from-chat/<slug:chat_name_slug>/<int:user_id>/',
         views.delete_user_from_chat, name='delete-from-chat'),
    path('leave-chat/<slug:chat_name_slug>/', views.leave_chat,
         name='leave-chat'),
]

triplinker/core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('accounts.urls')),
    path('feed/', include('feed.urls')),
    path('messages/', include('chat.urls')),
    path('places/', include('trip_places.urls')),
    path('journeys/', include('journeys.urls')),
    path('recommendations/', include('recommendations.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(path('debug/', include(debug_toolbar.urls)))

triplinker/feed/urls.py
from django.urls import path

from . import views


app_name = 'feed'

urlpatterns = [
    # Like/Unlike system.
    path('likes-api-post/<int:post_id>/', views.like_post_api,
         name="likes-api-post"),
    path('likes-api-comment/<int:comment_id>/', views.like_comment_api,
         name="likes-api-comment"),

    # Notifications
    path('notifications/', views.notifications_list,
         name="notifications"),
]

triplinker/journeys/urls.py
# Django modules.
from django.urls import path

# !Triplinker modules:

# Current app modules.
from . import views


app_name = 'journeys'

urlpatterns = [
    path('separate-journeys/<int:journey_id>/', views.journey_page,
         name='journey-page'),
    path('separate-journeys/<int:journey_id>/join', views.join_journey,
         name='join'),
    path('separate-journeys/<int:journey_id>/leave', views.leave_journey,
         name='leave'),
    path('separate-journeys/<int:journey_id>/remove/<int:user_id>',
         views.remove_from_journey, name='remove'),
    path('<int:user_id>/', views.user_journey_list,
         name='journey-list'),
    path('new-journey/', views.add_new_journey, name="new-journey"),
    path('edit-journey/<int:journey_id>/', views.edit_journey,
         name="edit-journey"),
    path('edit-activity/<int:activity_id>/', views.edit_activity,
         name="edit-activity"),

    # The sorting of journeys
    path('sort-by-date/<int:user_id>', views.sort_journeys_by_date,
         name="sort-journeys-by-date"),
    path('sort-by-rating/<int:user_id>', views.sort_journeys_by_rating_of_place,
         name="sort-journeys-by-rating-of-place"),
    path('journey-form-api/', views.journey_form_api,
         name="journey-form-api"),
    path('activity-form-api/', views.activity_form_api,
         name="activity-form-api"),
]

triplinker/trip_places/urls.py
# Django modules.
from django.urls import path

# !Triplinker modules:

# Current app modules.
from . import views


app_name = 'trip_places'

urlpatterns = [
    path('', views.all_places, name='all-places'),
    path('favourite-list/<int:user_id>/', views.favourite_places,
         name='favourite-places'),
    path('add-place/', views.add_place, name='add-place'),
    path('<int:place_id>', views.place_page, name='place-page'),
    path('<int:place_id>/photos', views.photos_of_place,
         name='photos-of-place'),
    path('<int:place_id>/feedback', views.comments_rating_page,
         name='rating-comments'),
    path('<int:place_id>/edit', views.edit_place_inf,
         name='edit-place'),
    path('favourite/<int:place_id>/', views.favourite_api,
         name="favourite"),
]

triplinker/feed/models.py
# Python modules.
import datetime

# Django modules.
from django.utils import timezone
from django.db import models
from django.core.validators import FileExtensionValidator

# !Triplinker modules:

# Another apps modules.
from accounts.models.TLAccount_frequest import TLAccount
from trip_places.models import Place

# Current app modules.
from journeys.models import Journey


class Post(models.Model):
    """Post model which provides users the possibility of posting thoughts,
    images and etc."""
    content = models.TextField()
    image = models.ImageField(upload_to='posts/', blank=True, null=True,
                              validators=[FileExtensionValidator(['png', 'jpg',
                                                                  'jpeg'])])
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(TLAccount, related_name='author', blank=True,
                               null=True, default=None,
                               on_delete=models.CASCADE)
    place = models.ForeignKey(Place, related_name='posts_of_place', null=True,
                              blank=True, on_delete=models.CASCADE)
    journey = models.ForeignKey(Journey, related_name='posts_of_journey',
                                null=True, blank=True, on_delete=models.CASCADE)
    likes = models.ManyToManyField(TLAccount, default=None, blank=True,
                                   related_name='like_system_post')

    is_place = models.BooleanField(default=False)
    notification_post = models.BooleanField(default=False)

    def __str__(self):
        return f'Author: {self.author}, content: {self.content[:20]}'

    def number_of_likes(self):
        return self.likes.all().count()

    def was_published_recently(self):
        return self.timestamp >= timezone.now() - datetime.timedelta(minutes=59)

    class Meta:
        ordering = ('-timestamp',)
        app_label = 'feed'
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'


class Comment(models.Model):
    """Model that are connected with post model because every post must have
    it's own comments"""

    user = models.ForeignKey(TLAccount, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField()
    likes = models.ManyToManyField(TLAccount, default=None, blank=True,
                                   related_name='like_system_comment')
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = 'feed'
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return ("User: {} | To post: {} |".format(self.user, self.post.author) +
                " Body: {}".format(self.body[:20]))


class Notification(models.Model):

    post = models.ForeignKey(Post, related_name="notifications",
                             on_delete=models.CASCADE)
    users = models.ManyToManyField(TLAccount, related_name="notifications")
    text = models.CharField("Notification text", max_length=250)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_seen = models.ManyToManyField(TLAccount, blank=True,
                                     related_name='seen_notifications')
    is_journey = models.BooleanField(default=False)

    def __str__(self):
        return f"Post {self.post}"

    class Meta:
        ordering = ('-timestamp',)
        app_label = 'feed'
        verbose_name = 'Notification'
        verbose_name_plural = 'Notifications'

triplinker/accounts/helpers/views/get_context_profile.py
# !Triplinker modules:

# Current app modules.
from accounts.models.TLAccount_frequest import FriendRequest
from accounts.feed_app_link import Post

# Current dir modules.
from .status_between_users_definer import define_status


def get_context_for_profile(request, user_acc, accType='another_user') -> dict:
    """Gets information about the profile user_acc."""
    context = None
    status_between_users = None
    try:
        amount_of_friends = user_acc.friends.all().count()
        amount_of_frequests = FriendRequest.objects.filter(
            to_user=user_acc.id).count()

        current_user = request.user
        another_user = user_acc

    except AttributeError:
        amount_of_friends = 0
        amount_of_frequests = 0

    if accType == 'another_user':
        status_between_users = define_status(FriendRequest, current_user,
                                             another_user)

    posts = Post.objects.filter(author=user_acc, is_place=False)
    notification_posts = Post.objects.filter(author=user_acc,
                                             notification_post=True)
    posts = posts | notification_posts

    user_avatar = None
    try:
        user_avatar = user_acc.get_avatar.all().first()
    except Exception:
        pass

    qualities = user_acc.qualities.all()
    qualities_3 = None
    qualities_more_than_3 = False
    other_qualities = None
    if len(qualities) > 3:
        qualities_more_than_3 = True
        qualities_3 = qualities[:3]
        other_qualities = qualities[3:]
    else:
        qualities_3 = qualities

    context = {
        'user_acc': user_acc,
        'who_makes_a_request': request.user.email,
        'amount_of_friends': amount_of_friends,
        'amount_of_frequests': amount_of_frequests,
        'status_between_users': status_between_users,
        'posts': posts,
        'avatar': user_avatar,
        'qualities': qualities_3,
        'qualities_more_than_3': qualities_more_than_3,
        'other_qualities': other_qualities
    }
    return context

triplinker/accounts/helpers/views/status_between_users_definer.py
def define_status(FriendRequest, current_user: int,
                  another_user: int) -> str:
    """Defines status between two users. Depending on the status the current
    user will be provided by a specific options.
    """
    frequest_case_1 = FriendRequest.objects.filter(
        from_user=current_user, to_user=another_user)

    frequest_case_2 = FriendRequest.objects.filter(
        from_user=another_user, to_user=current_user)

    we_wanna_be_friends_with_user = bool(frequest_case_1)
    user_wanna_be_friends_with_us = bool(frequest_case_2)

    status_between_users = None
    status_between_users  # for flake8, never used.
    if (we_wanna_be_friends_with_user is False and
            user_wanna_be_friends_with_us is True):
        return "User wanna be our friend"
    elif (we_wanna_be_friends_with_user is True and
          user_wanna_be_friends_with_us is False):
        return "We're waiting for user confirmation"
    elif (current_user in another_user.friends.all() and
          another_user in current_user.friends.all()):
        return "Friends"
    return "Not friends"

triplinker/accounts/views/all_views.py
# This module is needed to pass all functions(views) to the app's urls module.

# !Triplinker modules:

# Current app modules.
from accounts.views.all_users_list_view.all_users_list_view import *
from accounts.views.feed_view.feed_view import *
from accounts.views.followers_following_views.followers_following_views import *
from accounts.views.friends_system_views.friends_system_views import *
from accounts.views.followers_following_views.followers_following_views import *
from accounts.views.profile_views.additional_profile_views import *
from accounts.views.profile_views.main_profile_views import *
from accounts.views.reg_auth_acc_activate_views.views import *
from accounts.views.rest_api_views.views import *
from accounts.views.set_avatar_view.view import *
from accounts.views.user_photos_view.view import *

triplinker/accounts/views/rest_api_views/views.py
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.models.TLAccount_frequest import TLAccount
from accounts.serializers import TLAccountDetailSerializer


class TLAccountDetail(APIView):

    def get(self, request, user_id):
        usr = TLAccount.objects.get(id=user_id)
        serializer = TLAccountDetailSerializer(usr)
        return Response(serializer.data)

triplinker/accounts/templates/accounts/profile/photos_gallery.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/gallery.css' %}">
<script src="{% static 'accounts/js/photos_gallery.js'%}"></script>

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<script src="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>


  
    <div class="container" style="margin-top: 2%;margin-bottom:-3%;margin-left: -1%;text-align: center;">
        <h1 class="mt-2" style="display: inline;">· {{user_acc.email}} ·</h1>

        {% if request.user.email  == user_acc.email %}
            <!-- Button trigger modal -->
            <form method="post" enctype="multipart/form-data" style="margin-top: 1%;margin-bottom:0%;">
                {% csrf_token %}
                <h5 class="mt-1" style="text-align: center;">Share your photos!</h5>
                <input class="btn btn-primary" value="Upload photo" type="file" onchange="this.form.submit()" name="user_gallery_photo" title="your text"/>
            </form>
            {% endif %}
    </div>

    <!-- Page Content -->
   <div class="container page-top">
        <div class="row">
            {% if photos %}
            {% for photo_ in photos %}
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a href="{{ photo_.photo.url }}" class="fancybox" rel="ligthbox">
                    <img  src="{{photo_.photo.url}}" class="zoom img-fluid "  alt="">
                </a>
            </div>
            {% endfor %}
            {% else %}
            <p>It seems that the gallery has no photos yet.</p>
            {% endif %}
       </div>
    </div>
{% endblock %}

triplinker/accounts/templates/accounts/profile/profile_final_child_5.html
{% extends 'accounts/profile/profile_comments_4.html' %}
{% load static %}

{% block profile_final_child %}
{% endblock %}

triplinker/accounts/templates/accounts/profile/profile_header_1.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

<!--- Profile header[START] --->
    <div class="container db-social">
        <div class="jumbotron jumbotron-fluid"></div>
        <div class="container-fluid">
        <div class="row justify-content-center">
        <div class="col-xl-11">
        <div class="widget head-profile has-shadow">
        <div class="widget-body pb-0">
        <div class="row d-flex align-items-center">
        <div class="col-xl-4 col-md-4 d-flex justify-content-lg-start justify-content-md-start justify-content-center">
            <ul>
                <li>
                    <div class="counter">{{amount_of_friends}}</div>
                    {% if amount_of_friends == 1 %}
                        <div class="heading"><a href="{%url 'accounts:friends-list' user_acc.id%}">Friend</a></div>
                    {% else %}
                        <div class="heading"><a href="{%url 'accounts:friends-list' user_acc.id%}">Friends</a></div>
                    {% endif %}
                </li>
                    {% if user_acc.email == who_makes_a_request %}
                        <li>
                            <div class="counter">{{amount_of_frequests}}</div>
                            <div class="heading"><a href="{% url 'accounts:incoming-frequests' user_acc.id%}">Friend requests</a></div>
                        </li>
                    {% endif %}
            </ul>
        </div>

        <div class="col-xl-4 col-md-4 d-flex justify-content-center">
            {% if request.user.email == user_acc.email %}
            <!--- Avatar of the user [START] --->
                <a href="{% url 'accounts:set-avatar'%}">
                    <div class="image-default">
                        {% if avatar %}
                        <img class="rounded-circle" src="{{ avatar.profile_image.url }}" alt="avatar" width="110" height="120">
                        {% else %}
                        <img class="rounded-circle" src="https://www.xovi.com/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png" alt="avatar" width="110" height="120">
                        {% endif %}
                    </div>
                </a>
            <!--- Avatar of the user [END] --->
            {% else %}
                <div class="image-default">
                    {% if avatar %}
                        <img class="rounded-circle" src="{{ avatar.profile_image.url }}" alt="avatar" width="110" height="120">
                    {% else %}
                        <img class="rounded-circle" src="https://www.xovi.com/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png" alt="avatar" width="110" height="120">
                    {% endif %}
                </div>
            {% endif%}

            <div class="infos">
                <h2>{{user_acc.first_name}} {{user_acc.second_name}}</h2>
                <div class="location">{{user_acc.country}}</div>
            </div>
        </div>
        <div class="col-xl-4 col-md-4 d-flex justify-content-lg-end justify-content-md-end justify-content-center">
            <div class="follow">
                {% if user_acc.email == who_makes_a_request %}
                    <a class="btn btn-shadow btn btn-primary" href="{%url 'accounts:profile_edit' %}"><i class="la la-user-plus"></i>Edit account</a>

                {% elif user_acc.is_authenticated and user_acc.email != who_makes_a_request and status_between_users == "Not friends"%}

                    {% ifnotequal user_acc.can_get_message_from "Friends" %}
                        <a class="btn btn-shadow btn btn-primary" href="{% url 'chat:messages-dialog' user_acc.id%}"><i class="la la-user-plus"></i>Message</a>
                        <a title="Add this user to my friendlist" class="btn btn-shadow btn btn-dark" href="{%url 'accounts:send-frequest' user_acc.id%}"><i class="la la-user-plus" ></i>Add</a>
                    {% endifnotequal %}

                    {% ifnotequal user_acc.can_get_message_from "All" %}
                        <a title="Add this user to my friendlist" class="btn btn-shadow btn btn-dark" href="{%url 'accounts:send-frequest' user_acc.id%}"><i class="la la-user-plus" ></i>Add</a>
                    {% endifnotequal %}

                {% elif user_acc.is_authenticated and user_acc.email != who_makes_a_request and status_between_users == "User wanna be our friend" %}
                    <a class="btn btn-shadow btn btn-primary" href="{%url 'accounts:accept-frequest' user_acc.id%}"><i class="la la-user-plus"></i>Accept</a>

                    <a class="btn btn-shadow btn btn-danger" href="{% url 'accounts:delete-frequest' user_acc.id%}"><i class="la la-user-plus"></i>Dismiss</a>
                                            
                {% elif user_acc.is_authenticated and user_acc.email != who_makes_a_request and status_between_users == "We're waiting for user confirmation" %}

                    {% ifnotequal user_acc.can_get_message_from 'Friends' %}
                        <a class="btn btn-shadow btn btn-primary" href="{% url 'chat:messages-dialog' user_acc.id%}"><i class="la la-user-plus"></i>Message</a>
                        <a class="btn btn-shadow btn btn-danger" href="{%url 'accounts:cancel-frequest' user_acc.id %}"><i class="la la-user-plus"></i>Cancel</a>
                    {% endifnotequal %}

                    {% ifnotequal user_acc.can_get_message_from 'All' %}
                        <a class="btn btn-shadow btn btn-danger" href="{%url 'accounts:cancel-frequest' user_acc.id %}"><i class="la la-user-plus"></i>Cancel</a>
                    {% endifnotequal %}

                {% elif user_acc.is_authenticated and user_acc.email != who_makes_a_request and status_between_users == "Friends" %}
                    <a class="btn btn-shadow btn btn-primary" href="{% url 'chat:messages-dialog' user_acc.id%}"><i class="la la-user-plus"></i>Message</a>
                    <a class="btn btn-shadow btn btn-danger" href="{% url 'accounts:delete-friend' user_acc.id%}"><i class="la la-user-plus"></i>Delete</a>
                {% endif %}

        <div class="actions dark">
            <div class="dropdown">
                <button 
                type="button" 
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                class="dropdown-toggle">
                    <i class="la la-ellipsis-h"></i>
                </button>
                <div class="dropdown-menu" x-placement="bottom-start">
                    {% if user_acc.email == who_makes_a_request %}
                    <a href="{% url 'accounts:logout' %}">Logout</a>
                    {% else %}
                        {% if request.user in user_acc.followers.all and request.user not in user_acc.friends.all %}
                            <a href="{% url 'accounts:unfollow' user_acc.id%}" class="dropdown-item">Unfollow</a>
                        {% elif request.user not in user_acc.followers.all and request.user not in user_acc.friends.all %}
                            <a href="{% url 'accounts:follow' user_acc.id%}" class="dropdown-item">Follow</a>
                        {% endif %}

                    <a href="#" class="dropdown-item">Report</a>
                    <a href="#" class="dropdown-item">Block</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>

<!--- Profile header[END] --->

<!--- Feed [START] --->
{% block feed %}{% endblock %}
<!--- Feed [END] --->

{% endblock %}

triplinker/accounts/templates/accounts/profile/set_avatar_page.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

  <div class="container"> 
    <h1 class="mt-2">Set avatar</h1>
    <hr class="mt-0 mb-4">
      <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.field_errors }}
        {{ form.errors }}

        <div class='form-group row' style="margin-top: 2%;margin-bottom: 2%;">
          <div class="col-form-label col-sm-3 control-label">
          {{ form.profile_image.label }}
          </div>
          <div class="avatar avatar-xxl" style="margin-left: 1.5%;">
            {% if avatar %}
              <img class="rounded-circle" src="{{ avatar.profile_image.url }}" height="140" width="140" id="imgshow" alt="Current avatar">
            {% else %}
              <img class="rounded-circle" src="https://www.xovi.com/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png" alt="Default picture from" class="avatar-img rounded-circle" height="140" width="140" id="imgshow" alt="Default avatar">
            {% endif %}
          </div>
          
          <div class="col-sm-5" style="margin-top: 5%;">
            <input type="file" name="profile_image" id="imgload">
          </div>

        </div>

        <!--- Update photo on the page [START] --->
          <script type="text/javascript">
            $('document').ready(function () {
              $("#imgload").change(function () {
                if (this.files && this.files[0]) {
                  var reader = new FileReader();
                  reader.onload = function (e) {
                    $('#imgshow').attr('src', e.target.result);
                    }
                  reader.readAsDataURL(this.files[0]);
                }
              });
            });
          </script>
        <!--- Update photo on the page [END] --->

      <input type="submit" class="btn btn-primary" value="Set new avatar!" style="margin-left: 53.5%;margin-top: -1.5%;">
    </form>
  </div>
{% endblock %}