triplinker/accounts/urls.py
from django.urls import path, re_path, include

from .views import all_views as views


app_name = 'accounts'

urlpatterns = [
    # Home page.
    path('feed/', views.show_feed, name="feed"),

    # All users list.
    path('users/', views.all_users_list, name='all_users_list'),

    # SetAvatar.
    path('set-avatar/', views.set_avatar_view, name='set-avatar'),

    # User's photo gallery.
    path('users/<int:user_id>/photo-gallery/', views.photos_of_user,
         name='user-photo-gallery'),

    # A particular profile of user.
    path('users/<int:user_id>/', views.detail_profile,
         name="detail_profile"),

    # Friends system.
    path('users/<int:user_id>/incoming-friend-requests/',
         views.all_incoming_friquests_list, name="incoming-frequests"),
    path('users/<int:user_id>/outgoing-friend-riquests/',
         views.all_outgoing_friquests_list, name="outgoing-frequests"),
    path('users/<int:user_id>/friend-list/', views.friends_list,
         name="friends-list"),
    path('users/<int:user_id>/delete-friend/', views.delete_user_from_friends,
         name="delete-friend"),

    path('users/<int:user_id>/send-request/', views.send_request,
         name="send-frequest"),
    path('users/<int:user_id>/accept-request/', views.accept_friend_request,
         name="accept-frequest"),
    path('users/<int:user_id>/cancel-request/', views.cancel_friend_request,
         name="cancel-frequest"),
    path('users/<int:user_id>/delete-request/', views.delete_friend_request,
         name="delete-frequest"),

    # Followers and following.
    path('users/<int:user_id>/follow/', views.follow_user, name="follow"),
    path('users/<int:user_id>/unfollow/', views.unfollow_user, name="unfollow"),

    path('users/<int:user_id>/followers/', views.followers_list,
         name="followers-list"),
    path('users/<int:user_id>/following/', views.following_list,
         name="following-list"),

    # Profile, reg, auth.
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/', views.ActivateView.as_view(), name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(),
         name='profile_edit')
]


# Rest API
detail_profile_api_url = r'trip-linker-api/detail-profile/' \
                         r'(?P<user_id>\d{1,30})/?'
rest_api_patterns = [
    path('api-auth/', include('rest_framework.urls'),
         name='rest_framework'),
    re_path(r'(detail|profile|detail-profile)/(?P<user_id>\d+)/?',
            views.TLAccountDetail.as_view(),
            name='detail-profile-api')
]

urlpatterns += rest_api_patterns

triplinker/chat/urls.py
# Django modules.
from django.urls import path

# !Triplinker modules:

# Current app modules.
from .views import all_views as views


app_name = 'chat'

urlpatterns = [
    path('', views.messages_page, name='messages-page'),
    path('<int:user_id>/', views.messages_dialog_page,
         name='messages-dialog'),
    path('send-message-api/<int:user_id>/', views.send_message,
         name='send-message'),
    path('send-message-from-dialogs-page/',
         views.send_message_from_dialogs_page,
         name='send-message-from-dialogs-page'),
    path('get-all-messages-api/<int:user_id>/',
         views.get_all_messages, name='get-all-messages'),

    # GroupChat possibility.
    path('create-group-chat', views.create_group_chat,
         name='create-group-chat'),
    path('group-chats/', views.list_of_group_chats, name='group-chats'),
    path('<slug:chat_name_slug>/', views.particular_group_chat,
         name='particular-group-chat'),
    path('<slug:chat_name_slug>/send-message-group-chat-api/',
         views.send_message_in_group_chat, name='send-message-group-chat'),
    path('<slug:chat_name_slug>/get-all-messages-api/',
         views.get_all_messages_for_group_chat,
         name='get-all-messages-group-chat'),

    # GroupChat extra features.
    path('<slug:chat_name_slug>/participants/', views.view_participants,
         name='participants'),
    path('invite-person/<slug:chat_name_slug>/',
         views.invite_to_chat, name='invite-to-chat'),
    path('delete-from-chat/<slug:chat_name_slug>/<int:user_id>/',
         views.delete_user_from_chat, name='delete-from-chat'),
    path('leave-chat/<slug:chat_name_slug>/', views.leave_chat,
         name='leave-chat'),
]

triplinker/core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('accounts.urls')),
    path('feed/', include('feed.urls')),
    path('messages/', include('chat.urls')),
    path('places/', include('trip_places.urls')),
    path('journeys/', include('journeys.urls')),
    path('recommendations/', include('recommendations.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(path('debug/', include(debug_toolbar.urls)))

triplinker/chat/forms.py
# Django modules.
from django import forms

# !Triplinker modules:

# Another app modules.
from accounts.models.TLAccount_frequest import TLAccount

# Current app modules.
from .models import Message, GroupChat, GroupChatMainPhoto
from .helpers.get_query_set_not_participants import get_friends_not_participants


class SendMessageForm(forms.ModelForm):
    """The form that gives possility to send messages from messages page.
        chat:get-all-messages - view
    """
    def __init__(self, usr={}, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = TLAccount.objects.get(id=usr.id)
        self.queryset = self.user.friends.all()
        self.fields['to_user'].queryset = self.queryset

    message = forms.CharField(widget=forms.Textarea(attrs={
                                         'class': 'form-control',
                                         'rows': '5'}))

    to_user = forms.ModelChoiceField(queryset=TLAccount.objects.all())

    class Meta:
        model = Message
        fields = ['to_user', 'message']


class CreateGroupChatForm(forms.ModelForm):
    """The form to create group chat."""

    def __init__(self, usr={}, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = TLAccount.objects.get(id=usr.id)
        self.friends = self.user.friends.all()
        self.tuples = [(i.id, i.email) for i in self.friends]
        self.fields['participants'].choices = self.tuples

    chat_name = forms.CharField(widget=forms.TextInput(attrs={
                                     'class': 'form-control', }))

    OPTIONS = (('n', 'none'))
    widget = forms.CheckboxSelectMultiple
    participants = forms.MultipleChoiceField(widget=widget, choices=OPTIONS)

    def clean_chat_name(self):
        current_chat_name = self.cleaned_data['chat_name']

        chat_names = []
        chats = GroupChat.objects.all()
        for c in chats:
            chat_name = c.get_name()
            chat_names.append(chat_name)

        if current_chat_name in chat_names:
            msg = 'Chat with name %s is alredy exists' % current_chat_name
            raise forms.ValidationError(msg)
        return current_chat_name

    class Meta:
        model = GroupChat
        exclude = ['timestamp', ]


class ChatWithMainPhotoForm(forms.ModelForm):
    """The form to set main image of chat."""
    class Meta:
        model = GroupChatMainPhoto
        exclude = ['timestamp', ]


class InviteFriendToChatForm(forms.Form):
    """Using in groupchats to invite friends to the chat."""

    def __init__(self, usr, chat_slug_name, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = TLAccount.objects.get(id=usr.id)
        self.query = get_friends_not_participants(usr, chat_slug_name)
        self.tuples = [(i.id, i.email) for i in self.query]
        self.fields['participants'].choices = self.tuples

    OPTIONS = (('n', 'none'))
    widget = forms.CheckboxSelectMultiple
    participants = forms.MultipleChoiceField(widget=widget, choices=OPTIONS)

triplinker/chat/views/all_views.py
# This module is needed to pass all functions(views) to the app's urls module.

# !Triplinker modules:

# Current app modules.
from chat.views.dialog_views.views import *
from chat.views.group_chat_views.views import *

triplinker/chat/views/dialog_views/views.py
# Python modules.
import os
import json
import base64
from datetime import datetime

# Django Modules.
from django.core.files.images import ImageFile
from django.shortcuts import render, get_object_or_404
from django.http import (HttpResponseNotFound, HttpResponseRedirect,
                         JsonResponse)
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse

# !Triplinker modules:

# Another app module.
from accounts.models.TLAccount_frequest import TLAccount

# Current app modules.
from chat.tasks import get_associated_messages_task
from chat.models import Message, DialogPhoto
from chat.helpers.mssges_with_friends import get_last_mssges_from_dialogs
from chat.forms import SendMessageForm


def messages_page(request):
    """Page with user's messages (only dialogs)."""
    usr = get_object_or_404(TLAccount, id=request.user.id)
    last_messages = get_last_mssges_from_dialogs(usr)

    try:
        msg = sorted(last_messages, key=lambda msg: msg.timestamp, reverse=True)
        for message in msg:
            if message.from_user.email == usr.email:
                message.users_who_read_message.add(usr)

    # If user doesn't have friends and list 'last_messages' is empty
    except AttributeError:
        msg = None

    context = {
        'ordered_messages': msg,
        'form': SendMessageForm(usr=usr)
    }
    return render(request, 'chat/messages_page.html', context)


def messages_dialog_page(request, user_id):
    """The page with the dialog window."""
    current_user = get_object_or_404(TLAccount, id=request.user.id)
    message_to_user = get_object_or_404(TLAccount, id=user_id)

    if current_user.id == message_to_user.id:
        return HttpResponseNotFound()

    elif message_to_user.can_get_message_from == 'All':
        context = {
            'message_to_user': message_to_user,
        }
        return render(request, 'chat/messages_dialog.html', context)

    elif message_to_user.can_get_message_from == 'Friends':
        if (current_user not in message_to_user.friends.all() and
           message_to_user not in current_user.friends.all() and
           current_user not in message_to_user.strangers.all() and
           message_to_user not in current_user.strangers.all()):

            context = {
                'user_that_is_not_friend': message_to_user
            }
            return render(request, 'chat/message_error.html', context)

        elif (current_user not in message_to_user.friends.all() and
              message_to_user not in current_user.friends.all() and
              current_user in message_to_user.strangers.all() and
              message_to_user in current_user.strangers.all()):

            context = {
                'message_to_user': message_to_user,
            }
            return render(request, 'chat/messages_dialog.html', context)

        context = {
            'message_to_user': message_to_user,
        }
        return render(request, 'chat/messages_dialog.html', context)

    else:
        return HttpResponseNotFound()


@csrf_exempt
def send_message(request, user_id: int, dict_for_messages={}):
    """Iserts messages into DB."""
    from_user = TLAccount.objects.get(id=request.user.id)
    to_user = TLAccount.objects.get(id=user_id)
    is_dialog_page = dict_for_messages.get('is_dialog_page', None)

    if not is_dialog_page:
        message = request.POST.get("message_body", "")
    else:
        message = dict_for_messages['message']

    new_message = None
    if from_user in to_user.friends.all():
        new_message = Message.objects.create(
            from_user=from_user,
            to_user=to_user,
            message=message
        )
    elif (from_user not in to_user.friends.all() and
          to_user not in from_user.friends.all()):

        from_user.strangers.add(to_user)
        to_user.strangers.add(from_user)
        new_message = Message.objects.create(
            from_user=from_user,
            to_user=to_user,
            message=message
        )

    new_message.users_who_read_message.add(request.user)

    get_msg_with_photo = None
    imgs_url_for_fronted = None
    image_base64 = request.POST.get("image_or_nothing", "").partition(",")[2]
    if image_base64:
        decoding = base64.b64decode(image_base64)
        current_date = str(datetime.now())
        poFileStr = str(request.user) + current_date + '.jpg'

        cur_path = os.path.dirname(__file__)

        additional_dirs = 'public/media/'

    # .../triplinker/triplinker/public/media/chat/pictures_of_messages/image.jpg
    # ... - means system dirctories which are not connected with the project
    # Need to change cur_path.rstrip('chat') if the name of application will be
    # changed!
        new_path = cur_path.rstrip('chat') + additional_dirs + poFileStr
        new_path = ''.join(new_path)

        with open(new_path, 'wb') as f:
            f.write(decoding)

        new_msge_with_pic = DialogPhoto.objects.create(message=new_message,
                                                       name_of_file=poFileStr)
        new_msge_with_pic.image = ImageFile(open(new_path, "rb"))
        new_msge_with_pic.save()
        get_msg_with_photo = DialogPhoto.objects.get(name_of_file=poFileStr)

    json = {'author': str(new_message.from_user),
            'message_id': str(new_message.id)}

    try:
        image_url = get_msg_with_photo.image.url
        index = image_url.rfind('/media')
        imgs_url_for_fronted = image_url[index:]
        json['image_url'] = imgs_url_for_fronted
    except AttributeError:
        pass

    return JsonResponse(json, safe=False)


def send_message_from_dialogs_page(request):
    """The possibility of sending messages without rederecting to the dialog
    page with user."""
    usr = get_object_or_404(TLAccount, id=request.user.id)
    msg_to_another_user_form = SendMessageForm(usr, request.POST)
    if msg_to_another_user_form.is_valid():
        to_user = msg_to_another_user_form.cleaned_data.get('to_user')
        msg = msg_to_another_user_form.cleaned_data.get('message')
        another_user = TLAccount.objects.get(email=to_user)
        another_user_id = another_user.id
        dict_for_messages = {'message': msg, 'is_dialog_page': True}
        send_message(request, another_user.id, dict_for_messages)
        return HttpResponseRedirect(reverse('chat:messages-dialog',
                                    kwargs={'user_id': another_user_id}))


def get_all_messages(request, user_id):
    """Celery used view. Used in dialogs.Returns json response for FrontEnd
    with json ,which has following format:
    context[message.id] = [message.from_user.email, message.message,
                               image_or_none]
    * context is dict-like object.
    """
    messages = get_associated_messages_task.delay(request.user.id, user_id)
    parsed_json = json.loads(messages.get())
    return JsonResponse(parsed_json, safe=False)

triplinker/chat/templates/chat/create_group_chat.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

  <div class="container"> 
    <h1 class="mt-2">Create group chat</h1>
    <hr class="mt-0 mb-4">
      <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.field_errors }}
        {{ form.errors }}

        {{ form_photo.non_field_errors }}
        {{ form_photo.field_errors }}
        {{ form_photo.errors }}

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.chat_name.label }}
          </div>
          <div class="col-sm-5">
            {{ form.chat_name}}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.participants.label }}
          </div>
          <div class="col-sm-5">
            {{ form.participants }}
          </div>
        </div>

        <div class='form-group row' style="margin-top: 2%;margin-bottom: 2%;">
          <div class="col-form-label col-sm-3 control-label">
          {{ form.chat_image.label }}
          </div>
          <div class="avatar avatar-xxl" style="margin-left: 1.5%;">
            <img src="https://www.plotprojects.com/wp-content/uploads/2014/06/multiple-users.png" alt="Default picture from" class="avatar-img rounded-circle" height="140" width="140" id="imgshow">
          </div>
          
          <div class="col-sm-5" style="margin-top: 5%;">
            <input type="file" name="chat_image" id="imgload">
          </div>

        </div>

        <!--- Update photo on the page [START] --->
          <script type="text/javascript">
            $('document').ready(function () {
              $("#imgload").change(function () {
                if (this.files && this.files[0]) {
                  var reader = new FileReader();
                  reader.onload = function (e) {
                    $('#imgshow').attr('src', e.target.result);
                    }
                  reader.readAsDataURL(this.files[0]);
                }
              });
            });
          </script>
        <!--- Update photo on the page [END] --->

      <input type="submit" class="btn btn-primary" value="Create!" style="margin-left: 53.5%;margin-top: -1.5%;">
    </form>
  </div>

{% endblock %}

triplinker/chat/templates/chat/list_of_group_chats.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<div class="container" style="margin-left: 30%; margin-top: 2.2%;">
<div class="row">

<div class="col-md-8">

    <div class="chat_container">
        <div class="job-box">  
            <div class="job-box-filter">
                <div class="row">
                    
                    <div class="col-md-6 col-sm-6" style="margin-left: 50%;float: right">

                        <div class="filter-search-box text-right">
                            <label>Search:<input type="search" class="form-control input-sm" placeholder=""></label>
                        </div>
                    </div>
                </div>
            </div>
            <h3 type="button" style='display: inline; margin-left: 5%;' data-toggle="modal" data-target="#exampleModal"><i class="fa fa-envelope" aria-hidden="true" ></i></h3>

            <!-- modal triger button -->
            <a href="{% url 'chat:group-chats' %}" style="color:inherit;"><h3 style="margin-left: 3%; display: inline;"><i class="fa fa-users" aria-hidden="true"></i></h3></a>
            <!-- modal triger button -->


            <a href="{% url 'chat:create-group-chat' %}" style="color:inherit;"><h3 style="margin-left: 3%; display: inline;"><i class="fa fa-user-plus" aria-hidden="true"></i></h3></a>

            <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Send message or create group chat</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <form class="text-center border border-light p-6" method="post" style="margin-top: -2%;" action="{% url 'chat:send-message-from-dialogs-page' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Message: </label>
                                {{ form.message }}
                            </div>

                        <label>To: </label>
                        {{ form.to_user}}

                    <!-- Send button -->
                    
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-primary" value="Send message">
                      </div>
                    </div>
                  </div>
                </div>
                </form>

            <!-- modal -->

            <hr>
            <div class="inbox-message">
                {% if not group_chats %}

                    <p align="center" style="margin-top: 8%; margin-bottom: 0%;">You are not participating in any group chat.</p>
                {% elif group_chats %}
                {% for chat, list in group_chats.items %}
                <ul>
                    <li>
                        <a href="{% url 'chat:particular-group-chat' chat.slug %}">
                            <div class="message-avatar">
                                {% if list.1.chat_image %}
                                    <img src="{{ list.1.chat_image.url }}" alt="">
                                {% else %}
                                    <img src="https://www.plotprojects.com/wp-content/uploads/2014/06/multiple-users.png" alt="">
                                {% endif %}
                            </div>
                                <div class="message-body">
                                    <div class="message-body-heading">
                                        
                                        <h4>{{ chat.chat_name }}</h4>
                                        {% if list.0.message %}
                                            <span>{{ list.0.timestamp | timesince }} ago</span>
                                        {% endif %}
                                    </div>
                                    <p></p>

                                </div>
                                <div class="message-body">
                                    {% if list.0.message%}
                                        <div class="message-body-heading">
                                            <h6>{{ list.0.message }}</h6>
                                        </div>
                                        <p>by {{ list.0.msg_from_user}}</p>
                                    {% else %}
                                        <div class="message-body-heading">
                                            <h6>There are no messages in the chat yet</h6>
                                        </div>
                                    {% endif %}
                                </div>
                        </a>
                        <a href="{% url 'chat:leave-chat' chat.slug %}">
                            <div style="text-align: right;">
                                <div>   
                                    <h6 style="display: inline;">Leave </h6>
                                </div>
                                <h4 style="display: inline;"><i class="fa fa-sign-out" aria-hidden="true"></i></h4>
                            </div>
                        </a>
                    </li>
                </ul>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

triplinker/chat/templates/chat/message_error.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!</h1>
                <h2>
                    This user is not in your friendlist!</h2>
                <div class="error-details">
                    Sorry, an error has occured, to be able to send your message to this user you need to be the friend of him. 
                </div>
                <div class="error-actions">
                    <a href="{% url 'accounts:detail_profile' user_that_is_not_friend.id %}" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
                        Go to profile of {{ user_that_is_not_friend.email }}</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

triplinker/chat/templates/chat/participants_list.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="container" style="margin-top: 1%;margin-left: -1%;">
  <h1 class="mt-2" style="display: inline;">Participants</h1>
    <h3 style="display: inline; color:#0275d8; margin-left: 0.8%; cursor: pointer;" data-toggle="modal" data-target="#exampleModal">
      <i class="fa fa-plus-circle" aria-hidden="true">
      </i>
    </h3>
  <!-- modal code start -->
    <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Invite your friend to {{ chat.chat_name}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <form class="text-center border border-light p-6" method="post" style="margin-top: -2%;" action="{% url 'chat:invite-to-chat' chat.slug %}">
                            {% csrf_token %}
                        <label>To: </label>
                        <div style="text-align: left;">
                          {{ form.participants}}
                        </div>

                    <!-- Send button -->
                    
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-primary" value="Invite">
                      </div>
                    </div>
                  </div>
                </div>
                </form>
            <!-- modal -->
  <!-- modal code end -->
    <div class="row" style="margin-top: 1%;">
      <div class="col-md-8">
        <div class="people-nearby">
            {% for participant in particapants %}
              <div class="nearby-user">
                <div class="row">
                  <div class="col-md-2 col-sm-2">
                    {% if participant.get_avatar.all.first.profile_image %}
                      <img src="{{ participant.get_avatar.all.first.profile_image.url }}" alt="user" class="profile-photo-lg">
                    {% else %}
                      <img src="https://www.xovi.com/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png" alt="user" class="profile-photo-lg">
                    {% endif %}
                    
                  </div>
                  <div class="col-md-7 col-sm-7">
                    <h5><a href="{% url 'accounts:detail_profile' participant.id %}" class="profile-link">{{ participant.email }}</a></h5>
                    <p>{{participant.hobbies}}</p>
                    <p class="text-muted">500m away</p>
                  </div>
                  {% if request.user.email == chat.creator.email and request.user.email != participant.email %}
                  <div class="col-md-3 col-sm-3">
                    
                    <div class="btn-group" role="group" aria-label="Button group"style="margin-right:50%">
                      <a class="btn btn-danger" href="{% url 'chat:delete-from-chat' chat_name_slug=chat.slug user_id=participant.id %}" style="border-radius: 0.2rem;" role="button">Delete from chat</a>
                    </div>
                  </div>
                  {% endif %}
              </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}