triplinker/accounts/urls.py
from django.urls import path, re_path, include

from .views import all_views as views


app_name = 'accounts'

urlpatterns = [
    # Home page.
    path('feed/', views.show_feed, name="feed"),

    # All users list.
    path('users/', views.all_users_list, name='all_users_list'),

    # SetAvatar.
    path('set-avatar/', views.set_avatar_view, name='set-avatar'),

    # User's photo gallery.
    path('users/<int:user_id>/photo-gallery/', views.photos_of_user,
         name='user-photo-gallery'),

    # A particular profile of user.
    path('users/<int:user_id>/', views.detail_profile,
         name="detail_profile"),

    # Friends system.
    path('users/<int:user_id>/incoming-friend-requests/',
         views.all_incoming_friquests_list, name="incoming-frequests"),
    path('users/<int:user_id>/outgoing-friend-riquests/',
         views.all_outgoing_friquests_list, name="outgoing-frequests"),
    path('users/<int:user_id>/friend-list/', views.friends_list,
         name="friends-list"),
    path('users/<int:user_id>/delete-friend/', views.delete_user_from_friends,
         name="delete-friend"),

    path('users/<int:user_id>/send-request/', views.send_request,
         name="send-frequest"),
    path('users/<int:user_id>/accept-request/', views.accept_friend_request,
         name="accept-frequest"),
    path('users/<int:user_id>/cancel-request/', views.cancel_friend_request,
         name="cancel-frequest"),
    path('users/<int:user_id>/delete-request/', views.delete_friend_request,
         name="delete-frequest"),

    # Followers and following.
    path('users/<int:user_id>/follow/', views.follow_user, name="follow"),
    path('users/<int:user_id>/unfollow/', views.unfollow_user, name="unfollow"),

    path('users/<int:user_id>/followers/', views.followers_list,
         name="followers-list"),
    path('users/<int:user_id>/following/', views.following_list,
         name="following-list"),

    # Profile, reg, auth.
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/', views.ActivateView.as_view(), name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(),
         name='profile_edit')
]


# Rest API
detail_profile_api_url = r'trip-linker-api/detail-profile/' \
                         r'(?P<user_id>\d{1,30})/?'
rest_api_patterns = [
    path('api-auth/', include('rest_framework.urls'),
         name='rest_framework'),
    re_path(r'(detail|profile|detail-profile)/(?P<user_id>\d+)/?',
            views.TLAccountDetail.as_view(),
            name='detail-profile-api')
]

urlpatterns += rest_api_patterns

triplinker/chat/urls.py
# Django modules.
from django.urls import path

# !Triplinker modules:

# Current app modules.
from .views import all_views as views


app_name = 'chat'

urlpatterns = [
    path('', views.messages_page, name='messages-page'),
    path('<int:user_id>/', views.messages_dialog_page,
         name='messages-dialog'),
    path('send-message-api/<int:user_id>/', views.send_message,
         name='send-message'),
    path('send-message-from-dialogs-page/',
         views.send_message_from_dialogs_page,
         name='send-message-from-dialogs-page'),
    path('get-all-messages-api/<int:user_id>/',
         views.get_all_messages, name='get-all-messages'),

    # GroupChat possibility.
    path('create-group-chat', views.create_group_chat,
         name='create-group-chat'),
    path('group-chats/', views.list_of_group_chats, name='group-chats'),
    path('<slug:chat_name_slug>/', views.particular_group_chat,
         name='particular-group-chat'),
    path('<slug:chat_name_slug>/send-message-group-chat-api/',
         views.send_message_in_group_chat, name='send-message-group-chat'),
    path('<slug:chat_name_slug>/get-all-messages-api/',
         views.get_all_messages_for_group_chat,
         name='get-all-messages-group-chat'),

    # GroupChat extra features.
    path('<slug:chat_name_slug>/participants/', views.view_participants,
         name='participants'),
    path('invite-person/<slug:chat_name_slug>/',
         views.invite_to_chat, name='invite-to-chat'),
    path('delete-from-chat/<slug:chat_name_slug>/<int:user_id>/',
         views.delete_user_from_chat, name='delete-from-chat'),
    path('leave-chat/<slug:chat_name_slug>/', views.leave_chat,
         name='leave-chat'),
]

triplinker/core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('accounts.urls')),
    path('feed/', include('feed.urls')),
    path('messages/', include('chat.urls')),
    path('places/', include('trip_places.urls')),
    path('journeys/', include('journeys.urls')),
    path('recommendations/', include('recommendations.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(path('debug/', include(debug_toolbar.urls)))

triplinker/journeys/urls.py
# Django modules.
from django.urls import path

# !Triplinker modules:

# Current app modules.
from . import views


app_name = 'journeys'

urlpatterns = [
    path('separate-journeys/<int:journey_id>/', views.journey_page,
         name='journey-page'),
    path('separate-journeys/<int:journey_id>/join', views.join_journey,
         name='join'),
    path('separate-journeys/<int:journey_id>/leave', views.leave_journey,
         name='leave'),
    path('separate-journeys/<int:journey_id>/remove/<int:user_id>',
         views.remove_from_journey, name='remove'),
    path('<int:user_id>/', views.user_journey_list,
         name='journey-list'),
    path('new-journey/', views.add_new_journey, name="new-journey"),
    path('edit-journey/<int:journey_id>/', views.edit_journey,
         name="edit-journey"),
    path('edit-activity/<int:activity_id>/', views.edit_activity,
         name="edit-activity"),

    # The sorting of journeys
    path('sort-by-date/<int:user_id>', views.sort_journeys_by_date,
         name="sort-journeys-by-date"),
    path('sort-by-rating/<int:user_id>', views.sort_journeys_by_rating_of_place,
         name="sort-journeys-by-rating-of-place"),
    path('journey-form-api/', views.journey_form_api,
         name="journey-form-api"),
    path('activity-form-api/', views.activity_form_api,
         name="activity-form-api"),
]

triplinker/trip_places/urls.py
# Django modules.
from django.urls import path

# !Triplinker modules:

# Current app modules.
from . import views


app_name = 'trip_places'

urlpatterns = [
    path('', views.all_places, name='all-places'),
    path('favourite-list/<int:user_id>/', views.favourite_places,
         name='favourite-places'),
    path('add-place/', views.add_place, name='add-place'),
    path('<int:place_id>', views.place_page, name='place-page'),
    path('<int:place_id>/photos', views.photos_of_place,
         name='photos-of-place'),
    path('<int:place_id>/feedback', views.comments_rating_page,
         name='rating-comments'),
    path('<int:place_id>/edit', views.edit_place_inf,
         name='edit-place'),
    path('favourite/<int:place_id>/', views.favourite_api,
         name="favourite"),
]

triplinker/journeys/models.py
# Django modules.
from django.db import models

# !Triplinker modules:

# Another apps modules.
from accounts.models.TLAccount_frequest import TLAccount
from trip_places.models import Place


class Journey(models.Model):

    VISIBILITY_CHOICES = [
        ("All", "All users"),
        ("FriendsFollowers", "Friends & followers"),
        ("Friends", "Friends only"),
        ("Me", "Only me"),
    ]
    visibility = models.CharField("The level of visibility", max_length=16,
                                  choices=VISIBILITY_CHOICES, blank=False,
                                  null=True)
    journey_from = models.CharField("The point where the journey was started",
                                    max_length=35, blank=True, null=True)
    place_from = models.ForeignKey(Place, on_delete=models.CASCADE,
                                   related_name="start_places", blank=True,
                                   null=True)
    date_of_start = models.DateField(null=True)
    journey_to = models.CharField("The point where the journey was finished",
                                  max_length=35, blank=True,  null=True)
    place_to = models.ForeignKey(Place, on_delete=models.CASCADE,
                                 related_name="end_places", blank=True,
                                 null=True)
    date_of_end = models.DateField(null=True)

    vb_name_p = 'Particapants of the journey'

    participants = models.ManyToManyField(TLAccount,
                                          through='journeys.Participant',
                                          verbose_name=vb_name_p, blank=True,
                                          default=None,
                                          related_name='get_jrns')

    description = models.TextField("Describe your journey", max_length=500,
                                   blank=True, null=True)
    vb_name_who = "The person who has created the journey's page"

    acc = TLAccount
    who_added_the_journey = models.ForeignKey(acc, verbose_name=vb_name_who,
                                              related_name='who_added',
                                              on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        format_s = self.journey_from, self.journey_to, self.place_from
        return 'From: {}, to: {}, start place: {}'.format(*format_s)

    def get_visibility(self):
        return self.visibility

    def check_instance(self):
        return 'Journey'

    class Meta:
        ordering = ('-timestamp',)
        app_label = 'journeys'
        verbose_name = 'Journey'
        verbose_name_plural = 'Journeys'


class Participant(models.Model):
    journey = models.ForeignKey(Journey, on_delete=models.CASCADE, null=True)
    participant = models.ForeignKey(TLAccount, on_delete=models.CASCADE,
                                    related_name='participant_set', null=True)

    def __str__(self):
        jrn_s = self.journey.journey_from
        jrn_f = self.journey.journey_to
        partic = self.participant.email
        return "Journey: {} - {}, participant: {}".format(jrn_s, jrn_f, partic)


class Activity(models.Model):
    journey = models.ForeignKey(Journey, related_name="activities",
                                on_delete=models.CASCADE, blank=True, null=True)
    description = models.CharField("Description of activity",
                                   max_length=35, blank=True, null=True)
    place = models.ForeignKey(Place, on_delete=models.CASCADE,
                              related_name="places", blank=True, null=True)
    date_of_start = models.DateField(null=True, blank=True,)
    date_of_end = models.DateField(null=True, blank=True,)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"Journey {self.journey}"

    class Meta:
        ordering = ('-timestamp',)
        app_label = 'journeys'
        verbose_name = 'Activity'
        verbose_name_plural = 'Activities'

triplinker/journeys/forms.py
# Django modules.
from django import forms

# !Triplinker modules:

# Current app modules.
from .models import Journey, Activity


class AddJourneyForm(forms.ModelForm):
    journey_from = forms.CharField(widget=forms.TextInput(attrs={
                                     'class': 'form-control', }))
    date_of_start = forms.DateField(widget=forms.DateInput(attrs={
                                     'class': 'form-control',
                                     'type': 'date'}))
    journey_to = forms.CharField(widget=forms.TextInput(attrs={
                                     'class': 'form-control'}))

    date_of_end = forms.DateField(widget=forms.DateInput(attrs={
                                     'class': 'form-control',
                                     'type': 'date'}))
    description = forms.CharField(widget=forms.Textarea(attrs={
                                     'class': 'form-control',
                                     'rows': '5'}))

    class Meta:
        model = Journey
        fields = ['journey_from', 'place_from', 'date_of_start', 'journey_to',
                  'place_to', 'date_of_end', 'description', 'visibility']


class AddActivityForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={
                                     'class': 'form-control',
                                     'rows': '5'}))

    date_of_start = forms.DateField(widget=forms.DateInput(attrs={
                                    'class': 'form-control',
                                    'type': 'date'}))

    date_of_end = forms.DateField(widget=forms.DateInput(attrs={
                                    'class': 'form-control',
                                    'type': 'date'}))

    class Meta:
        model = Activity
        fields = ['description', 'place', 'date_of_start',
                  'date_of_end']

triplinker/journeys/helpers/views/get_allowed_journeys.py
# !Triplinker modules:

# Current app modules.
from journeys.models import Journey


def get_allowed_journeys(current_user, another_user) -> list:
    all_journeys_of_user = Journey.objects.filter(participants=another_user)
    permitted_journeys = []
    if current_user.email != another_user.email:
        for journey in all_journeys_of_user:
            if current_user not in journey.participants.all():
                visibility_of_journey = journey.get_visibility()
                if visibility_of_journey == 'FriendsFollowers':
                    if (current_user in another_user.friends.all() or
                       current_user in another_user.followers.all()):
                        permitted_journeys.append(journey)

                elif visibility_of_journey == 'Friends':
                    if current_user in another_user.friends.all():
                        permitted_journeys.append(journey)

                elif visibility_of_journey == 'Me':
                    continue
                else:
                    permitted_journeys.append(journey)
        return permitted_journeys
    else:
        return all_journeys_of_user

triplinker/journeys/helpers/views/get_average_rating.py
def get_rating(journey) -> int:
    place_1_rating = journey.place_from.get_rating_of_place()
    place_2_rating = journey.place_to.get_rating_of_place()
    avg_rating = (place_1_rating + place_2_rating) / 2
    return avg_rating

triplinker/journeys/templates/journeys/add_journey_form.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

  <div class="container">
    <h1 class="mt-2">Create new journey</h1>
    <hr class="mt-0 mb-4">
      <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.field_errors }}
        {{ form.errors }}
        <div id="main">
          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ form.journey_from.label }}
            </div>
            <div class="col-sm-5">
              {{ form.journey_from}}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ form.place_from.label }}
            </div>
            <div class="col-sm-5">
              {{ form.place_from}}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ form.date_of_start.label }}
            </div>
            <div class="col-sm-5">
              {{ form.date_of_start }}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ form.journey_to.label }}
            </div>
            <div class="col-sm-5">
              {{ form.journey_to }}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ form.place_to.label }}
            </div>
            <div class="col-sm-5">
              {{ form.place_to}}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ form.date_of_end.label }}
            </div>
            <div class="col-sm-5">
              {{ form.date_of_end }}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ form.particapants.label }}
            </div>
            <div class="col-sm-5">
              {{ form.particapants }}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ form.visibility.label }}
            </div>
            <div class="col-sm-5">
              {{ form.visibility }}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ form.description.label }}
            </div>
            <div class="col-sm-5">
            {{ form.description }}
            </div>
          </div>

          <hr>
        </div>




        <div id="activities">

        </div>

        <div class="clone">
          <div class="btn btn-danger float-right fa fa-times" id="cancel" aria-hidden="true"></div>
          <h3></h3>
          <hr>
          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ activity_form.description.label }}
            </div>
            <div class="col-sm-5">
              {{ activity_form.description }}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ activity_form.place.label }}
            </div>
            <div class="col-sm-5">
              {{ activity_form.place }}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ activity_form.date_of_start.label }}
            </div>
            <div class="col-sm-5">
              {{ activity_form.date_of_start }}
            </div>
          </div>

          <div class='form-group row'>
            <div class="col-form-label col-sm-3 control-label">
              {{ activity_form.date_of_end.label }}
            </div>
            <div class="col-sm-5">
              {{ activity_form.date_of_end }}
            </div>
          </div>
          <hr>
        </div>
        <div class="float-left">
          <a id="add-activity" class="btn btn-primary float-left text-light">Add one more activity</a>
          <script type="text/javascript">
            $(document).ready(function(){
                let activity = $(".clone").clone();
                $(".clone").remove();
                let n = 0;
                $("#add-activity").on('click',function(event){
                  n++;
                  let c_activity = activity.clone();
                  c_activity.removeClass("clone").addClass("activities");
                  c_activity.attr("id", "activity" + n);
                  c_activity.children("h3").text(n + " activity");
                  if (n > 1) {
                    $("#activity" + (n - 1)).children("#cancel").remove();
                  }
                  $("#activities").append(c_activity);
                });
                $(document).on('click', "#cancel",function(event){
                  $("#activity" + n).remove();
                  n--;
                  $("#activity" + n).prepend("<div class='btn btn-danger float-right fa fa-times' id='cancel' aria-hidden='true'></div>");
                });
                let j_id = -1;
                $("#submit-form").on('click',function(event){
                  // Making asynchronous request to the server.
                  $.ajax({
                    type: "POST",
                    url: "{% url 'journeys:journey-form-api' %}",
                    data: {'journey_from': $('#id_journey_from').val(), 

                    'place_from': $('#id_place_from').find(':selected').val(), 'date_of_start': $('#main').find('#id_date_of_start').val(), 'journey_to': $('#id_journey_to').val(),
                    'visibility': $('#id_visibility').find(':selected').val(),
                    'place_to': $('#id_place_to').find(':selected').val(), 
                    'date_of_end': $('#main').find('#id_date_of_end').val(), 
                    'description': $('#id_description').val(), 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                    dataType: 'json',

                    success: function(data){
                      j_id = data['journey_id'];
                      if (data['status']) {
                        for (let i = 1; i <= n; i++) {
                          $.ajax({
                            type: "POST",
                            url: "{% url 'journeys:activity-form-api' %}",
                            data: {'place': $('#activity' + i).find('#id_place').find(':selected').val(), 'date_of_start':  $('#activity' + i).find('#id_date_of_start').val(), 'journey_id': j_id,
                            'date_of_end':  $('#activity' + i).find('#id_date_of_end').val(), 'description':  $('#activity' + i).find('#id_description').val(), 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                            dataType: 'json',
                            success: function(data){
                            },
                            error: function(rs, e) {
                              alert('Activity');
                            }
                          });
                        }
                      }
                    },
                    error: function(rs, e) {
                      alert(rs.responseText);
                    }
                  });
                });
            })
          </script>
        </div>
      <button id="submit-form" class="btn btn-primary float-right text-light">Add new journey!</button>
    </form>
  </div>

{% endblock %}

triplinker/journeys/templates/journeys/edit_activity.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

  <div class="container">
    <h1 class="mt-2">Edit activity</h1>
    <hr class="mt-0 mb-4">
      <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.field_errors }}
        {{ form.errors }}

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.description.label }}
          </div>
          <div class="col-sm-5">
            {{ form.description }}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.place.label }}
          </div>
          <div class="col-sm-5">
            {{ form.place }}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.date_of_start.label }}
          </div>
          <div class="col-sm-5">
            {{ form.date_of_start }}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.date_of_end.label }}
          </div>
          <div class="col-sm-5">
            {{ form.date_of_end }}
          </div>
        </div>
      <button class="btn btn-primary float-right text-light">Edit</button>
    </form>
  </div>

{% endblock %}

triplinker/journeys/templates/journeys/edit_journey.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

  <div class="container">
    <h1 class="mt-2">Create new journey</h1>
    <hr class="mt-0 mb-4">
      <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.field_errors }}
        {{ form.errors }}
        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.journey_from.label }}
          </div>
          <div class="col-sm-5">
            {{ form.journey_from}}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.place_from.label }}
          </div>
          <div class="col-sm-5">
            {{ form.place_from}}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.date_of_start.label }}
          </div>
          <div class="col-sm-5">
            {{ form.date_of_start }}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.journey_to.label }}
          </div>
          <div class="col-sm-5">
            {{ form.journey_to }}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.place_to.label }}
          </div>
          <div class="col-sm-5">
            {{ form.place_to}}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.date_of_end.label }}
          </div>
          <div class="col-sm-5">
            {{ form.date_of_end }}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.particapants.label }}
          </div>
          <div class="col-sm-5">
            {{ form.particapants }}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.visibility.label }}
          </div>
          <div class="col-sm-5">
            {{ form.visibility }}
          </div>
        </div>

        <div class='form-group row'>
          <div class="col-form-label col-sm-3 control-label">
            {{ form.description.label }}
          </div>
          <div class="col-sm-5">
            {{ form.description }}
          </div>
        </div>
      <button class="btn btn-primary float-right text-light">Edit</button>
    </form>
  </div>

{% endblock %}

triplinker/journeys/templates/journeys/user_journeys_list.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

{% block css%}
<link rel="stylesheet" type="text/css" href="{% static 'journeys/journeys_list.css'%}">

{% endblock %}

{% if request.user.email == user_acc.email %}
<div class="container" style="text-align: center;margin-top: 1%;">
  <h1 class="mt-2" style=" display: inline;">Your journeys</h1>
  <a href="{% url 'journeys:new-journey'%}">
    <h3 style="display: inline; color:#0275d8;margin-left: 0.8%;">
      <i class="fa fa-plus-circle" aria-hidden="true">
      </i>
    </h3>
  </a>
</div>
{% else %}
<div class="container">
  <h1 class="mt-2" style="text-align: center;">Journeys of {{user_acc.name}}</h1>
</div>
{% endif %}
</div>
<div class="container" style="text-align: center; margin-top: 1%;">
  {% if request.user.email == user_acc.email %}
    <a href="{% url 'journeys:journey-list' request.user.id %}"><button class="btn btn-dark">Default</button></a>
  {% else %}
    <a href="{% url 'journeys:journey-list' user_acc.id %}"><button class="btn btn-dark">Default</button></a>
  {% endif %}
  <a href="{% url 'journeys:sort-journeys-by-date' user_acc.id %}"><button class="btn btn-dark">Sort by date</button></a>
  <a href="{% url 'journeys:sort-journeys-by-rating-of-place' user_acc.id %}"><button class="btn btn-dark">Sort by rating of place</button></a>

</div>
{% if journeys %}
<div class="container" style="margin-top: 2%;">
  <div class="row">
  
  {% for journey in journeys %}
  <div class="col-sm-4 py-2">
    <div class="card text-white bg-light">
      <div class="card-body">
        <div name='info' style="color:black;">
          <h3 class="card-title">{{ journey.journey_from}} - {{ journey.journey_to }}</h3>
            <p class="card-text">{{ journey.description }}</p>
            <hr>
            <p class="card-text">Started: {{ journey.date_of_start }}</p>
            <p class="card-text">Ended: {{ journey.date_of_end }}</p>
            <p class="card-text">From : <a href="{% url 'trip_places:place-page' journey.place_from.id%}" style="color: inherit;">{{ journey.place_from.name_of_place }} ({{ journey.place_from.get_rating_of_place }} ★)</a></p>
            <p class="card-text">To : <a href="{% url 'trip_places:place-page' journey.place_from.id%}" style="color: inherit;">{{ journey.place_to.name_of_place }} ({{ journey.place_to.get_rating_of_place }} ★)</a></p>
            <p class="card-text">Location: {{ journey.place_to.location }} - {{ journey.place_to.location}}</p>
            
            {% if journey.participant_set.all %}
            <hr>
            <p class="card-text" style="text-align: center;">Particapants: </p>
            {% for participant in journey.participant_set.all %}
            <p class="card-text">• <a style="color: inherit;" href="{% url 'accounts:detail_profile' participant.participant.id %}">{{participant.participant.first_name}} {{participant.participant.second_name}} </a></p>
            {% endfor %}
            {% endif %}

            <a href="{% url 'journeys:journey-page' journey.id %}" class="btn btn-success">Check it out</a>
            </div>
          </div>
            </div>
        </div>
  {% endfor %}
    </div>

</div>

{% else %}
  <p style="text-align: center;margin-top: 2%;">There are no journeys here.</p>
{% endif %}
{% endblock %}