triplinker/accounts/urls.py
from django.urls import path, re_path, include

from .views import all_views as views


app_name = 'accounts'

urlpatterns = [
    # Home page.
    path('feed/', views.show_feed, name="feed"),

    # All users list.
    path('users/', views.all_users_list, name='all_users_list'),

    # SetAvatar.
    path('set-avatar/', views.set_avatar_view, name='set-avatar'),

    # User's photo gallery.
    path('users/<int:user_id>/photo-gallery/', views.photos_of_user,
         name='user-photo-gallery'),

    # A particular profile of user.
    path('users/<int:user_id>/', views.detail_profile,
         name="detail_profile"),

    # Friends system.
    path('users/<int:user_id>/incoming-friend-requests/',
         views.all_incoming_friquests_list, name="incoming-frequests"),
    path('users/<int:user_id>/outgoing-friend-riquests/',
         views.all_outgoing_friquests_list, name="outgoing-frequests"),
    path('users/<int:user_id>/friend-list/', views.friends_list,
         name="friends-list"),
    path('users/<int:user_id>/delete-friend/', views.delete_user_from_friends,
         name="delete-friend"),

    path('users/<int:user_id>/send-request/', views.send_request,
         name="send-frequest"),
    path('users/<int:user_id>/accept-request/', views.accept_friend_request,
         name="accept-frequest"),
    path('users/<int:user_id>/cancel-request/', views.cancel_friend_request,
         name="cancel-frequest"),
    path('users/<int:user_id>/delete-request/', views.delete_friend_request,
         name="delete-frequest"),

    # Followers and following.
    path('users/<int:user_id>/follow/', views.follow_user, name="follow"),
    path('users/<int:user_id>/unfollow/', views.unfollow_user, name="unfollow"),

    path('users/<int:user_id>/followers/', views.followers_list,
         name="followers-list"),
    path('users/<int:user_id>/following/', views.following_list,
         name="following-list"),

    # Profile, reg, auth.
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/', views.ActivateView.as_view(), name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(),
         name='profile_edit')
]


# Rest API
detail_profile_api_url = r'trip-linker-api/detail-profile/' \
                         r'(?P<user_id>\d{1,30})/?'
rest_api_patterns = [
    path('api-auth/', include('rest_framework.urls'),
         name='rest_framework'),
    re_path(r'(detail|profile|detail-profile)/(?P<user_id>\d+)/?',
            views.TLAccountDetail.as_view(),
            name='detail-profile-api')
]

urlpatterns += rest_api_patterns

triplinker/chat/urls.py
# Django modules.
from django.urls import path

# !Triplinker modules:

# Current app modules.
from .views import all_views as views


app_name = 'chat'

urlpatterns = [
    path('', views.messages_page, name='messages-page'),
    path('<int:user_id>/', views.messages_dialog_page,
         name='messages-dialog'),
    path('send-message-api/<int:user_id>/', views.send_message,
         name='send-message'),
    path('send-message-from-dialogs-page/',
         views.send_message_from_dialogs_page,
         name='send-message-from-dialogs-page'),
    path('get-all-messages-api/<int:user_id>/',
         views.get_all_messages, name='get-all-messages'),

    # GroupChat possibility.
    path('create-group-chat', views.create_group_chat,
         name='create-group-chat'),
    path('group-chats/', views.list_of_group_chats, name='group-chats'),
    path('<slug:chat_name_slug>/', views.particular_group_chat,
         name='particular-group-chat'),
    path('<slug:chat_name_slug>/send-message-group-chat-api/',
         views.send_message_in_group_chat, name='send-message-group-chat'),
    path('<slug:chat_name_slug>/get-all-messages-api/',
         views.get_all_messages_for_group_chat,
         name='get-all-messages-group-chat'),

    # GroupChat extra features.
    path('<slug:chat_name_slug>/participants/', views.view_participants,
         name='participants'),
    path('invite-person/<slug:chat_name_slug>/',
         views.invite_to_chat, name='invite-to-chat'),
    path('delete-from-chat/<slug:chat_name_slug>/<int:user_id>/',
         views.delete_user_from_chat, name='delete-from-chat'),
    path('leave-chat/<slug:chat_name_slug>/', views.leave_chat,
         name='leave-chat'),
]

triplinker/core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('accounts.urls')),
    path('feed/', include('feed.urls')),
    path('messages/', include('chat.urls')),
    path('places/', include('trip_places.urls')),
    path('journeys/', include('journeys.urls')),
    path('recommendations/', include('recommendations.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(path('debug/', include(debug_toolbar.urls)))

triplinker/feed/urls.py
from django.urls import path

from . import views


app_name = 'feed'

urlpatterns = [
    # Like/Unlike system.
    path('likes-api-post/<int:post_id>/', views.like_post_api,
         name="likes-api-post"),
    path('likes-api-comment/<int:comment_id>/', views.like_comment_api,
         name="likes-api-comment"),

    # Notifications
    path('notifications/', views.notifications_list,
         name="notifications"),
]

triplinker/recommendations/urls.py
from django.urls import path

from . import views


app_name = 'recommendations'

urlpatterns = [
    path('', views.all_recommendations, name='all-recommendations'),
    path('journeys-only/', views.jouneys_only, name='journeys-only'),
    path('places-only', views.places_only, name='places-only'),
]

triplinker/trip_places/urls.py
# Django modules.
from django.urls import path

# !Triplinker modules:

# Current app modules.
from . import views


app_name = 'trip_places'

urlpatterns = [
    path('', views.all_places, name='all-places'),
    path('favourite-list/<int:user_id>/', views.favourite_places,
         name='favourite-places'),
    path('add-place/', views.add_place, name='add-place'),
    path('<int:place_id>', views.place_page, name='place-page'),
    path('<int:place_id>/photos', views.photos_of_place,
         name='photos-of-place'),
    path('<int:place_id>/feedback', views.comments_rating_page,
         name='rating-comments'),
    path('<int:place_id>/edit', views.edit_place_inf,
         name='edit-place'),
    path('favourite/<int:place_id>/', views.favourite_api,
         name="favourite"),
]

triplinker/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Triplinker</title>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <!--- accounts app [START] --->
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/all_users_list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile_head.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/comment_section.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile_feed.css'%}">

  <!--- Notification bell [END] --->
  <script type="text/javascript" src="{% static 'accounts/js/comments.js'%}"></script>
  <!--- accounts app [END] --->

  <!--- chat app [START] --->
  <link rel="stylesheet" type="text/css" href="{% static 'chat/css/all_messages_page.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'chat/css/messages_dialog.css'%}">

  <link rel="stylesheet" type="text/css" href="{% static 'chat/css/message_error.css'%}">
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <!--- chat app [END] --->

  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"crossorigin="anonymous">

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  {% block css %}
  {% endblock %}

  {% block additional_links%}
  {% endblock%}

</head>
<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      {% if request.user.is_authenticated %}
      <a href="{% url 'accounts:feed' %}" class="navbar-brand">Triplinker</a>
      {% else %}
      <span class="navbar-brand">Triplinker</span>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:profile' %}"><h5 style="display:inline;"><i class="fa fa-user" aria-hidden="true"></i></h5> Profile</a>

            {% if new_messages %}
              <a class="nav-item nav-link" href="{% url 'chat:messages-page' %}"><h5 style="display:inline;"><i class="fa fa-comments" aria-hidden="true"></i></h5> Messages <span style = 'color:white;background-color: #d15b47!important;' class="badge badge-important">{{number_of_new_messages}}</span></a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'chat:messages-page' %}"><h5 style="display:inline;"><i class="fa fa-comments" aria-hidden="true"></i></h5> Messages</a>
            {% endif %}

            <a class="nav-item nav-link" href="{% url 'accounts:feed' %}"><h5 style="display:inline;"><i class="fa fa-globe" aria-hidden="true"></i></h5> Feed</a>
            <a class="nav-item nav-link" href="{% url 'accounts:all_users_list' %}"><h5 style="display:inline;"><i class="fa fa-users" aria-hidden="true"></i></h5> People</a>

            <a class="nav-item nav-link" href="{% url 'trip_places:all-places' %}"><h5 style="display:inline;"><i class="fa fa-map-marker" aria-hidden="true"></i></h5> Places</a>
            <a class="nav-item nav-link" href="{% url 'recommendations:all-recommendations' %}"><h5 style="display:inline;"><i class="fa fa-suitcase" aria-hidden="true"></i></h5> Recommendations</a>
            <a class="nav-item nav-link {% if user not in user.notifications.last.is_seen.all %} text-danger {% endif %}" href="{% url 'feed:notifications' %}"><h5 style="display:inline;"><i class="fa fa-bell" aria-hidden="true"></i></h5> Notifications</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">login</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">signup</a>
          {% endif %}
        </div>
        {% if user.is_authenticated %}
        <form class="form-inline ml-auto" action="{% url 'accounts:all_users_list' %}" method="get">
          <input class="form-control mr-sm-2" type="search" aria-label="Search" name="q" placeholder="Search...">
          <button class="btn btn-outline-light my-sm-0" type="submit">Search</button>
        </form>
        {% endif %}
      </div>
    </nav>
  </header>

  <main>
    <script type="text/javascript">
    $(document).ready(function(){
      {% block jQuery %}{% endblock %}
  })
  </script>

    <div class="container">
      <div class="row justify-content-center">
        {% block main %}
        {% endblock %}
      </div>
    </div>
  </main>

  <footer>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  {% block javascript %}
  {% endblock %}
</body>
</html>